w3c/ColorWeb-CG

- png_cicp_chunk_proposal.md
This commit adds a proposal to ammend the PNG specification to
add support for a new cICP chunk that enabled HDR support.
Closes #11
> Add support for HDR imagery to the PNG format

- png_cicp_chunk_proposal.md
During the 2021-02-24 meeting there was interest in supporting narrow range in PNGs. This implies the requirement of YUV support in PNG.
PNG doesn't currently have a way to specify different sizes for different planes. Until that is added, formats like 4:2:0 cannot be used. However, 4:4:4 is a possibility.
This pull request adds wording for enabling YUV 4:4:4 support to PNG.
Closes #16
> Add MATCOEFFS

- hdr_html_canvas_element.md
Add a new proposal for HDR compositing of HTMLCanvasElement.
> Add HDR compositing of HTMLCanvasElement proposal

- hdr-in-png-requirements.md
A missing newline caused a reference to appear as a continuation of a the previous reference.
This commit inserts the missing newline.
> Fix formatting

- hdr_html_canvas_element.md
Remove much of the text and focus on API changes and examples.
Give an algorithm for converting HLG and PQ to XYZD50 and leave it at that (no discussion of device independent light -- just have XYZD50 do that job).
Move discussion of making HDR compositing mode independent of the canvas color space to the end of the document.
> Simplify HDR proposal

- hdr_html_canvas_element.md
This was left out of the previous patch. Also fix a heading typo.
> Remove enabled:true that is no longer needed

- hdr-in-png-requirements.md
The proposed cICP chunk is currently described as 3 bytes. That is
then followed by how it actually uses 4 bytes.
This commit corrects the description to always list the cICP chunk
as 4 bytes.
Closes #21
> cICP chunk is 4 bytes, not 3

- hdr-in-png-requirements.md
Currently, the HDR in PNG proposal points out that it is different
from JPEG-XL because this would use 1 byte instead of 2. But
JPEG-XL also uses 1 byte.
The real difference is this proposal uses H.273 where JPEG-XL
cherry picked a handful of color spaces and left room for custom
values.
This commit corrects the 1 vs. 2 byte description and clarifies the
H.273 difference.
Closes #28
> JPEG-XL uses 1 byte, not 2

- hdr-in-png-requirements.md
The HDR in PNG proposal currently says the only difference between
the iCCP and iCCN chunks is Latin-1 vs. UTF-8 profile names.
But this is not completely correct. The PNG spec explicitly says
iCCP is ICCv2. Although many decoders treat iCCP as ICCv4, the
iCCN chunk would be explicitly ICCv4.
This commit clarifies this distinction.
Closes #30
> iCCP and iCCN specify different ICC versions

- hdr-in-png-requirements.md
The HDR in PNG proposal was a strict order of what chunks should cause
others to be ignored. However, a piece of it is missing and must be
inferred.
This commit clearly spells the ignored chunks.
Closs #34
> Specify that a cICP chunk should ignore iCCP chunks

- hdr-in-png-requirements.md
Currently, the proposal references BT.2100-1 explicitly, despite
linking to the unversioned BT.2100. It seems like the -1 version
is not actually an important detail.
This commit removes the version and instead references the
future-proof, unversioned BT.2100.
Closes #26
> Reference unversioned BT.2100

- hdr_html_canvas_element.md
The definitions of the color spaces are separated from the specification of the conversion between them.
Since the XYZD50 color system was introduced merely for mathematical expediency, it is replaced with the BT.2100 color system. This removes the need for a white point conversion since sRGB, HLG and PQ share the same D65 white point. 
Closes #37
> Clarify color space definitions

- hdr_html_canvas_element.md
> Fix typos in Extended RGB colorspace definitions

- hdr-in-png-requirements.md
The proposal currently specifies the ASCII values along with the
characters that represent the chunk identifier.
The ASCII values are unneeded. The characters are clear enough on
their own.
This commit removes the ASCII values.
> Remove superfluous wording

- hdr-in-png-requirements.md
There is a table that isn't showing as such in the markdown format.
There is also two separate sections that are currently in one paragraph.
This commit fixes those two formatting issues.
> Clean formatting

- hdr-in-png-requirements.md
Currently, the proposal mentions the details of two chunks without
explaining that these two chunks are the proposed new chunks to
address the issue.
To people who were at the meetings, it may be clear enough. But to
an external reader, it could seem like a mind dump without clarity.
This commit explicitly states that the two chunks are new to this
proposal and how they should work.
> Explicitly state two proposed chunks

- index.html
Corrected some minor spelling, grammar, and HTML issues. Examples include:
* "colorspaces" -> "color spaces"
* "matt" -> "matte"
* "4k" -> "4K"
* "wre" -> "were"
* "&" -> "&amp;"
* space after comma
Replaced some special Unicode characters with their HTML encoded entities or equivalents (e.g. "<sup>2</sup>" for the Unicode superscript 2 character, "&trade;" for the TM character).
Reformatted the HTML with a 120 character line width using Prettier.
> Correct some spelling, grammar, and HTML issues

- hdr_html_canvas_element.md
Add parameters to ScreenAdvanced, through which precise HDR and WCG parameters may be queried.
> Add ScreenAdvanced parameters

- hdr-in-png-requirements.md
The existing HDR in PNG requirements doc lists the 'sRGB' chunk as
lowest priority.
However, the PNG spec [1] says that the 'sRGB' chunk has a higher priority
than 'gAMA' and 'cHRM', as it is short-hand for an exact set of 'gAMA'
and 'cHRM' values.
This commit corrects the priority order of the PNG chunks.
[1] https://www.w3.org/TR/2003/REC-PNG-20031110/#11sRGB
> Correct priority order of PNG chunks.

- hdr_html_canvas_element.md
Following https://chromium-review.googlesource.com/c/chromium/src/+/3890974, this PR adds a new `smpteSt2086Metadata` dictionary to `CanvasHighDynamicRangeOptions` to specify HDR metadata to an HDR canvas.
@ccameron-chromium PTAL
> Add smpteSt2086Metadata to CanvasHighDynamicRangeOptions

- hdr-in-png-requirements.md
If the cICP specifies a code point which the decoder knows cannot be
used by the display / surface, the cICP chunk should be ignored. This
commit adds that wording.
> Clarify cICP fallthrough

- hdr_html_canvas_element.md
* specify that color volume metadata defines the nominal color volume of the image content
* specify how mastering display metadata can be used to set color volume metadata
* provide an example of how color volume metadata is used when tone mapping
* specify that color volume metadata should be used when rendering a temporal sequence of images
Closes #97
> Clarify the use of color volume metadata

- hdr_html_canvas_element.md
> Clarify expectactions for `toDataURL()` and `toBlob()`
